- README.md
Just a few phrasing edits, no substantive changes.
> Simplify language in readme

- bios/github-teacher.md
What would you like to know about me?
> Stub of githubteacher bio

- bios/cuanbio
> Cuan's bio created

- bios/jon-rules-more-than-bob.md
> create jon-rules-more-than-bob file to show bob who really rules

- bios/sdutta.md
> Started bio of Sagar

- bios/mandar.md
This is a new branch and new file
> Creating a new bio

- bios/bob-rules.md
> Great work, Bob... you're winning this class

- bios/lnario-mybadneedanother.md
> Started lnario bio

- bios/marandamir_jon-glas.md
> Create new bios file for marandamir

- SG_BIO.md
> Stated SG Bio

- bios/cynthia-rich.md
:warning: WIP :warning:
This is my bio. What else should I include?
> Started Cynthia Rich Bio

- bios/manish-bhatia.md
:+1: WIP :warning: 
This is my bio
> Started md file for manish's  bio

- bios/john-hardy.md
> Created Bio for JHardy

- bios/matt-gerde.md
:warning: :construction: :warning: 
This is my bio.  Please let me know if you have any suggestions.
> Started Matt Gerde Bio

- bios/janjaap.md
> I like to commit changes

- bios/justin-russell.md
:warning: Work in Progress :warning: 
Silly @rwnilsen3 and @marandamir debating who is more ruling than the other. Those of us that are truly awesome don't have to always announce it. We just exude it.
My bio is bland. What else should I add.
> Create stub of justin russell bio

- bios/SonaliTestAnother
> Create Stub of sonali bio

- bios/subramaniants.md
> Started subramaniants bio

- bios/larryfuqua.md
What kinds of things should I add to my bio.
> Stub for bio for LarryFuqua

- bios/jacmorel.md
> jacmorel's bio
